// Code generated by protoc-gen-go.
// source: s2c/container.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/container.proto

It has these top-level messages:
	ContainerInfo
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContainerOP int32

const (
	ContainerOP_OP_ADD      ContainerOP = 1
	ContainerOP_OP_REMOVE   ContainerOP = 2
	ContainerOP_OP_MODIFY   ContainerOP = 3
	ContainerOP_OP_EXCHANGE ContainerOP = 4
)

var ContainerOP_name = map[int32]string{
	1: "OP_ADD",
	2: "OP_REMOVE",
	3: "OP_MODIFY",
	4: "OP_EXCHANGE",
}
var ContainerOP_value = map[string]int32{
	"OP_ADD":      1,
	"OP_REMOVE":   2,
	"OP_MODIFY":   3,
	"OP_EXCHANGE": 4,
}

func (x ContainerOP) Enum() *ContainerOP {
	p := new(ContainerOP)
	*p = x
	return p
}
func (x ContainerOP) String() string {
	return proto.EnumName(ContainerOP_name, int32(x))
}
func (x *ContainerOP) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ContainerOP_value, data, "ContainerOP")
	if err != nil {
		return err
	}
	*x = ContainerOP(value)
	return nil
}

type ContainerInfo struct {
	Op               *ContainerOP `protobuf:"varint,1,req,name=op,enum=s2c.ContainerOP" json:"op,omitempty"`
	Ctype            *int32       `protobuf:"varint,2,req,name=ctype" json:"ctype,omitempty"`
	Src              *int32       `protobuf:"varint,3,req,name=src" json:"src,omitempty"`
	Dest             *int32       `protobuf:"varint,4,opt,name=dest" json:"dest,omitempty"`
	SrcItem          *string      `protobuf:"bytes,5,req,name=src_item" json:"src_item,omitempty"`
	DestItem         *string      `protobuf:"bytes,6,opt,name=dest_item" json:"dest_item,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ContainerInfo) Reset()         { *m = ContainerInfo{} }
func (m *ContainerInfo) String() string { return proto.CompactTextString(m) }
func (*ContainerInfo) ProtoMessage()    {}

func (m *ContainerInfo) GetOp() ContainerOP {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return ContainerOP_OP_ADD
}

func (m *ContainerInfo) GetCtype() int32 {
	if m != nil && m.Ctype != nil {
		return *m.Ctype
	}
	return 0
}

func (m *ContainerInfo) GetSrc() int32 {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return 0
}

func (m *ContainerInfo) GetDest() int32 {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return 0
}

func (m *ContainerInfo) GetSrcItem() string {
	if m != nil && m.SrcItem != nil {
		return *m.SrcItem
	}
	return ""
}

func (m *ContainerInfo) GetDestItem() string {
	if m != nil && m.DestItem != nil {
		return *m.DestItem
	}
	return ""
}

func init() {
	proto.RegisterEnum("s2c.ContainerOP", ContainerOP_name, ContainerOP_value)
}
