// Code generated by protoc-gen-go.
// source: s2c/createobject.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/createobject.proto

It has these top-level messages:
	CreateObject
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateObject struct {
	Self             *bool   `protobuf:"varint,1,req,name=self" json:"self,omitempty"`
	Index            *int32  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Serial           *int32  `protobuf:"varint,3,opt,name=serial" json:"serial,omitempty"`
	Entity           *string `protobuf:"bytes,4,req,name=entity" json:"entity,omitempty"`
	Typ              *int32  `protobuf:"varint,5,req,name=typ" json:"typ,omitempty"`
	Propinfo         []byte  `protobuf:"bytes,6,req,name=propinfo" json:"propinfo,omitempty"`
	Mailbox          *string `protobuf:"bytes,7,opt,name=mailbox" json:"mailbox,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateObject) Reset()         { *m = CreateObject{} }
func (m *CreateObject) String() string { return proto.CompactTextString(m) }
func (*CreateObject) ProtoMessage()    {}

func (m *CreateObject) GetSelf() bool {
	if m != nil && m.Self != nil {
		return *m.Self
	}
	return false
}

func (m *CreateObject) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CreateObject) GetSerial() int32 {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return 0
}

func (m *CreateObject) GetEntity() string {
	if m != nil && m.Entity != nil {
		return *m.Entity
	}
	return ""
}

func (m *CreateObject) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

func (m *CreateObject) GetPropinfo() []byte {
	if m != nil {
		return m.Propinfo
	}
	return nil
}

func (m *CreateObject) GetMailbox() string {
	if m != nil && m.Mailbox != nil {
		return *m.Mailbox
	}
	return ""
}
