// Code generated by protoc-gen-go.
// source: s2c/enterscene.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/enterscene.proto

It has these top-level messages:
	EnterScene
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EnterScene struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterScene) Reset()         { *m = EnterScene{} }
func (m *EnterScene) String() string { return proto.CompactTextString(m) }
func (*EnterScene) ProtoMessage()    {}

func (m *EnterScene) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}
