// Code generated by protoc-gen-go.
// source: s2c/error.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/error.proto

It has these top-level messages:
	Error
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Error struct {
	ErrorNo          *int32 `protobuf:"varint,1,req,name=error_no" json:"error_no,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetErrorNo() int32 {
	if m != nil && m.ErrorNo != nil {
		return *m.ErrorNo
	}
	return 0
}
