// Code generated by protoc-gen-go.
// source: s2c/loginsucceed.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/loginsucceed.proto

It has these top-level messages:
	Loginsucceed
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Loginsucceed struct {
	Host             *string `protobuf:"bytes,1,req,name=host" json:"host,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	Key              *int32  `protobuf:"varint,3,req,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Loginsucceed) Reset()         { *m = Loginsucceed{} }
func (m *Loginsucceed) String() string { return proto.CompactTextString(m) }
func (*Loginsucceed) ProtoMessage()    {}

func (m *Loginsucceed) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *Loginsucceed) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *Loginsucceed) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}
