// Code generated by protoc-gen-go.
// source: s2c/motion.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/motion.proto

It has these top-level messages:
	Motion
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Motion struct {
	Self             *bool    `protobuf:"varint,1,req,name=self" json:"self,omitempty"`
	Index            *int32   `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Serial           *int32   `protobuf:"varint,3,opt,name=serial" json:"serial,omitempty"`
	X                *float32 `protobuf:"fixed32,4,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,5,req,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,6,req,name=z" json:"z,omitempty"`
	Dir              *float32 `protobuf:"fixed32,7,req,name=dir" json:"dir,omitempty"`
	State            *string  `protobuf:"bytes,8,req,name=state" json:"state,omitempty"`
	ParentIndex      *int32   `protobuf:"varint,9,opt,name=parentIndex" json:"parentIndex,omitempty"`
	ParentSerial     *int32   `protobuf:"varint,10,opt,name=parentSerial" json:"parentSerial,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Motion) Reset()         { *m = Motion{} }
func (m *Motion) String() string { return proto.CompactTextString(m) }
func (*Motion) ProtoMessage()    {}

func (m *Motion) GetSelf() bool {
	if m != nil && m.Self != nil {
		return *m.Self
	}
	return false
}

func (m *Motion) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Motion) GetSerial() int32 {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return 0
}

func (m *Motion) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Motion) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Motion) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *Motion) GetDir() float32 {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return 0
}

func (m *Motion) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Motion) GetParentIndex() int32 {
	if m != nil && m.ParentIndex != nil {
		return *m.ParentIndex
	}
	return 0
}

func (m *Motion) GetParentSerial() int32 {
	if m != nil && m.ParentSerial != nil {
		return *m.ParentSerial
	}
	return 0
}
