// Code generated by protoc-gen-go.
// source: s2c/respreceivetask.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/respreceivetask.proto

It has these top-level messages:
	Respreceivetask
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Respreceivetask struct {
	Taskid           *string `protobuf:"bytes,1,req,name=taskid" json:"taskid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Respreceivetask) Reset()         { *m = Respreceivetask{} }
func (m *Respreceivetask) String() string { return proto.CompactTextString(m) }
func (*Respreceivetask) ProtoMessage()    {}

func (m *Respreceivetask) GetTaskid() string {
	if m != nil && m.Taskid != nil {
		return *m.Taskid
	}
	return ""
}
