// Code generated by protoc-gen-go.
// source: s2c/rpc.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/rpc.proto

It has these top-level messages:
	Rpc
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Rpc struct {
	Sender           *string `protobuf:"bytes,1,req,name=sender" json:"sender,omitempty"`
	Servicemethod    *string `protobuf:"bytes,2,req,name=servicemethod" json:"servicemethod,omitempty"`
	Data             []byte  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Rpc) Reset()         { *m = Rpc{} }
func (m *Rpc) String() string { return proto.CompactTextString(m) }
func (*Rpc) ProtoMessage()    {}

func (m *Rpc) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *Rpc) GetServicemethod() string {
	if m != nil && m.Servicemethod != nil {
		return *m.Servicemethod
	}
	return ""
}

func (m *Rpc) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}
