// Code generated by protoc-gen-go.
// source: s2c/updateproperty.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/updateproperty.proto

It has these top-level messages:
	UpdateProperty
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UpdateProperty struct {
	Self             *bool  `protobuf:"varint,1,req,name=self" json:"self,omitempty"`
	Index            *int32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Serial           *int32 `protobuf:"varint,3,opt,name=serial" json:"serial,omitempty"`
	Propinfo         []byte `protobuf:"bytes,4,req,name=propinfo" json:"propinfo,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateProperty) Reset()         { *m = UpdateProperty{} }
func (m *UpdateProperty) String() string { return proto.CompactTextString(m) }
func (*UpdateProperty) ProtoMessage()    {}

func (m *UpdateProperty) GetSelf() bool {
	if m != nil && m.Self != nil {
		return *m.Self
	}
	return false
}

func (m *UpdateProperty) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *UpdateProperty) GetSerial() int32 {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return 0
}

func (m *UpdateProperty) GetPropinfo() []byte {
	if m != nil {
		return m.Propinfo
	}
	return nil
}
