// Code generated by protoc-gen-go.
// source: s2c/updaterecord.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/updaterecord.proto

It has these top-level messages:
	CreateRecord
	RecordAddRow
	RecordDelRow
	RecordSetRow
	RecordGrid
	RecordClear
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateRecord struct {
	Record           *string `protobuf:"bytes,1,req,name=record" json:"record,omitempty"`
	Rows             *int32  `protobuf:"varint,2,req,name=rows" json:"rows,omitempty"`
	Cols             *int32  `protobuf:"varint,3,req,name=cols" json:"cols,omitempty"`
	Recinfo          []byte  `protobuf:"bytes,4,opt,name=recinfo" json:"recinfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRecord) Reset()         { *m = CreateRecord{} }
func (m *CreateRecord) String() string { return proto.CompactTextString(m) }
func (*CreateRecord) ProtoMessage()    {}

func (m *CreateRecord) GetRecord() string {
	if m != nil && m.Record != nil {
		return *m.Record
	}
	return ""
}

func (m *CreateRecord) GetRows() int32 {
	if m != nil && m.Rows != nil {
		return *m.Rows
	}
	return 0
}

func (m *CreateRecord) GetCols() int32 {
	if m != nil && m.Cols != nil {
		return *m.Cols
	}
	return 0
}

func (m *CreateRecord) GetRecinfo() []byte {
	if m != nil {
		return m.Recinfo
	}
	return nil
}

type RecordAddRow struct {
	Record           *string `protobuf:"bytes,1,req,name=record" json:"record,omitempty"`
	Row              *int32  `protobuf:"varint,2,req,name=row" json:"row,omitempty"`
	Rowinfo          []byte  `protobuf:"bytes,3,req,name=rowinfo" json:"rowinfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecordAddRow) Reset()         { *m = RecordAddRow{} }
func (m *RecordAddRow) String() string { return proto.CompactTextString(m) }
func (*RecordAddRow) ProtoMessage()    {}

func (m *RecordAddRow) GetRecord() string {
	if m != nil && m.Record != nil {
		return *m.Record
	}
	return ""
}

func (m *RecordAddRow) GetRow() int32 {
	if m != nil && m.Row != nil {
		return *m.Row
	}
	return 0
}

func (m *RecordAddRow) GetRowinfo() []byte {
	if m != nil {
		return m.Rowinfo
	}
	return nil
}

type RecordDelRow struct {
	Record           *string `protobuf:"bytes,1,req,name=record" json:"record,omitempty"`
	Row              *int32  `protobuf:"varint,2,req,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecordDelRow) Reset()         { *m = RecordDelRow{} }
func (m *RecordDelRow) String() string { return proto.CompactTextString(m) }
func (*RecordDelRow) ProtoMessage()    {}

func (m *RecordDelRow) GetRecord() string {
	if m != nil && m.Record != nil {
		return *m.Record
	}
	return ""
}

func (m *RecordDelRow) GetRow() int32 {
	if m != nil && m.Row != nil {
		return *m.Row
	}
	return 0
}

type RecordSetRow struct {
	Record           *string `protobuf:"bytes,1,req,name=record" json:"record,omitempty"`
	Row              *int32  `protobuf:"varint,2,req,name=row" json:"row,omitempty"`
	Rowinfo          []byte  `protobuf:"bytes,3,req,name=rowinfo" json:"rowinfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecordSetRow) Reset()         { *m = RecordSetRow{} }
func (m *RecordSetRow) String() string { return proto.CompactTextString(m) }
func (*RecordSetRow) ProtoMessage()    {}

func (m *RecordSetRow) GetRecord() string {
	if m != nil && m.Record != nil {
		return *m.Record
	}
	return ""
}

func (m *RecordSetRow) GetRow() int32 {
	if m != nil && m.Row != nil {
		return *m.Row
	}
	return 0
}

func (m *RecordSetRow) GetRowinfo() []byte {
	if m != nil {
		return m.Rowinfo
	}
	return nil
}

type RecordGrid struct {
	Record           *string `protobuf:"bytes,1,req,name=record" json:"record,omitempty"`
	Row              *int32  `protobuf:"varint,2,req,name=row" json:"row,omitempty"`
	Col              *int32  `protobuf:"varint,3,req,name=col" json:"col,omitempty"`
	Gridinfo         []byte  `protobuf:"bytes,4,req,name=gridinfo" json:"gridinfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecordGrid) Reset()         { *m = RecordGrid{} }
func (m *RecordGrid) String() string { return proto.CompactTextString(m) }
func (*RecordGrid) ProtoMessage()    {}

func (m *RecordGrid) GetRecord() string {
	if m != nil && m.Record != nil {
		return *m.Record
	}
	return ""
}

func (m *RecordGrid) GetRow() int32 {
	if m != nil && m.Row != nil {
		return *m.Row
	}
	return 0
}

func (m *RecordGrid) GetCol() int32 {
	if m != nil && m.Col != nil {
		return *m.Col
	}
	return 0
}

func (m *RecordGrid) GetGridinfo() []byte {
	if m != nil {
		return m.Gridinfo
	}
	return nil
}

type RecordClear struct {
	Record           *string `protobuf:"bytes,1,req,name=record" json:"record,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecordClear) Reset()         { *m = RecordClear{} }
func (m *RecordClear) String() string { return proto.CompactTextString(m) }
func (*RecordClear) ProtoMessage()    {}

func (m *RecordClear) GetRecord() string {
	if m != nil && m.Record != nil {
		return *m.Record
	}
	return ""
}
