// Code generated by protoc-gen-go.
// source: s2c/viewport.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/viewport.proto

It has these top-level messages:
	CreateView
	DeleteView
	ViewProperty
	ViewAdd
	ViewRemove
	ViewobjProperty
	ViewExchange
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 添加视窗
type CreateView struct {
	ViewId           *int32  `protobuf:"varint,1,req" json:"ViewId,omitempty"`
	Entity           *string `protobuf:"bytes,2,req" json:"Entity,omitempty"`
	Capacity         *int32  `protobuf:"varint,3,req" json:"Capacity,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateView) Reset()         { *m = CreateView{} }
func (m *CreateView) String() string { return proto.CompactTextString(m) }
func (*CreateView) ProtoMessage()    {}

func (m *CreateView) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

func (m *CreateView) GetEntity() string {
	if m != nil && m.Entity != nil {
		return *m.Entity
	}
	return ""
}

func (m *CreateView) GetCapacity() int32 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

// 删除视窗
type DeleteView struct {
	ViewId           *int32 `protobuf:"varint,1,req" json:"ViewId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteView) Reset()         { *m = DeleteView{} }
func (m *DeleteView) String() string { return proto.CompactTextString(m) }
func (*DeleteView) ProtoMessage()    {}

func (m *DeleteView) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

// 视窗属性
type ViewProperty struct {
	ViewId           *int32 `protobuf:"varint,1,req" json:"ViewId,omitempty"`
	Props            []byte `protobuf:"bytes,2,opt" json:"Props,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ViewProperty) Reset()         { *m = ViewProperty{} }
func (m *ViewProperty) String() string { return proto.CompactTextString(m) }
func (*ViewProperty) ProtoMessage()    {}

func (m *ViewProperty) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

func (m *ViewProperty) GetProps() []byte {
	if m != nil {
		return m.Props
	}
	return nil
}

// 视窗中添加对象
type ViewAdd struct {
	ViewId           *int32  `protobuf:"varint,1,req" json:"ViewId,omitempty"`
	Index            *int32  `protobuf:"varint,2,req" json:"Index,omitempty"`
	Entity           *string `protobuf:"bytes,3,req" json:"Entity,omitempty"`
	Props            []byte  `protobuf:"bytes,4,opt" json:"Props,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ViewAdd) Reset()         { *m = ViewAdd{} }
func (m *ViewAdd) String() string { return proto.CompactTextString(m) }
func (*ViewAdd) ProtoMessage()    {}

func (m *ViewAdd) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

func (m *ViewAdd) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ViewAdd) GetEntity() string {
	if m != nil && m.Entity != nil {
		return *m.Entity
	}
	return ""
}

func (m *ViewAdd) GetProps() []byte {
	if m != nil {
		return m.Props
	}
	return nil
}

// 视窗中删除对象
type ViewRemove struct {
	ViewId           *int32 `protobuf:"varint,1,req" json:"ViewId,omitempty"`
	Index            *int32 `protobuf:"varint,2,req" json:"Index,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ViewRemove) Reset()         { *m = ViewRemove{} }
func (m *ViewRemove) String() string { return proto.CompactTextString(m) }
func (*ViewRemove) ProtoMessage()    {}

func (m *ViewRemove) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

func (m *ViewRemove) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

// 视窗中对象的属性
type ViewobjProperty struct {
	ViewId           *int32 `protobuf:"varint,1,req" json:"ViewId,omitempty"`
	Index            *int32 `protobuf:"varint,2,req" json:"Index,omitempty"`
	Props            []byte `protobuf:"bytes,3,opt" json:"Props,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ViewobjProperty) Reset()         { *m = ViewobjProperty{} }
func (m *ViewobjProperty) String() string { return proto.CompactTextString(m) }
func (*ViewobjProperty) ProtoMessage()    {}

func (m *ViewobjProperty) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

func (m *ViewobjProperty) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ViewobjProperty) GetProps() []byte {
	if m != nil {
		return m.Props
	}
	return nil
}

// 交换视窗对象
type ViewExchange struct {
	ViewId1          *int32 `protobuf:"varint,1,req" json:"ViewId1,omitempty"`
	Index1           *int32 `protobuf:"varint,2,req" json:"Index1,omitempty"`
	ViewId2          *int32 `protobuf:"varint,3,req" json:"ViewId2,omitempty"`
	Index2           *int32 `protobuf:"varint,4,req" json:"Index2,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ViewExchange) Reset()         { *m = ViewExchange{} }
func (m *ViewExchange) String() string { return proto.CompactTextString(m) }
func (*ViewExchange) ProtoMessage()    {}

func (m *ViewExchange) GetViewId1() int32 {
	if m != nil && m.ViewId1 != nil {
		return *m.ViewId1
	}
	return 0
}

func (m *ViewExchange) GetIndex1() int32 {
	if m != nil && m.Index1 != nil {
		return *m.Index1
	}
	return 0
}

func (m *ViewExchange) GetViewId2() int32 {
	if m != nil && m.ViewId2 != nil {
		return *m.ViewId2
	}
	return 0
}

func (m *ViewExchange) GetIndex2() int32 {
	if m != nil && m.Index2 != nil {
		return *m.Index2
	}
	return 0
}
