// Code generated by protoc-gen-go.
// source: s2c/visibleobject.proto
// DO NOT EDIT!

/*
Package s2c is a generated protocol buffer package.

It is generated from these files:
	s2c/visibleobject.proto

It has these top-level messages:
	Visibleobject
*/
package s2c

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Visibleobject struct {
	Self             *bool  `protobuf:"varint,1,req,name=self" json:"self,omitempty"`
	Index            *int32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Serial           *int32 `protobuf:"varint,3,opt,name=serial" json:"serial,omitempty"`
	Visible          *bool  `protobuf:"varint,4,req,name=visible" json:"visible,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Visibleobject) Reset()         { *m = Visibleobject{} }
func (m *Visibleobject) String() string { return proto.CompactTextString(m) }
func (*Visibleobject) ProtoMessage()    {}

func (m *Visibleobject) GetSelf() bool {
	if m != nil && m.Self != nil {
		return *m.Self
	}
	return false
}

func (m *Visibleobject) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Visibleobject) GetSerial() int32 {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return 0
}

func (m *Visibleobject) GetVisible() bool {
	if m != nil && m.Visible != nil {
		return *m.Visible
	}
	return false
}
