// Code generated by data parser.
// DO NOT EDIT!
package entity

import (
	. "server/data/datatype"
	"encoding/gob"
)

//获取类型
func GetType(name string) int {
	switch name { {{range .}}
	case "{{.Name}}":
		return {{.Type}}{{end}}
	default:
		return NONE
	}
}

func CreateSaveLoader(typ string) DBSaveLoader {
	switch typ { {{range .}}
	case "{{.Name}}":
		return &{{.Name}}_Save{}{{end}}
	default:
		return nil
	}
}

func Hash(str string) int32 {
	hash := 5381
	for _, c := range str {
		hash += (hash << 5) + int(c)
	}

	return int32(hash & 0x7FFFFFFF)
}

{{range .}}
func Is{{.Name}}(ent Entityer) bool {
		return ent.ObjTypeName()=="{{.Name}}"
}
{{end}}

//初始化函数
func init() {
	{{range .}}
	Register("{{.Name}}", func() Entityer {
		return Create{{.Name}}()
	})
	{{.Name}}Init()
	{{end}}

	gob.Register(&EntityInfo{})
}
