// Code generated by protoc-gen-go.
// source: c2s/controlview.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/controlview.proto

It has these top-level messages:
	Controlview
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Controlview struct {
	Viewid           *int32 `protobuf:"varint,1,req,name=viewid" json:"viewid,omitempty"`
	Op               *int32 `protobuf:"varint,2,req,name=op" json:"op,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Controlview) Reset()         { *m = Controlview{} }
func (m *Controlview) String() string { return proto.CompactTextString(m) }
func (*Controlview) ProtoMessage()    {}

func (m *Controlview) GetViewid() int32 {
	if m != nil && m.Viewid != nil {
		return *m.Viewid
	}
	return 0
}

func (m *Controlview) GetOp() int32 {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return 0
}
