// Code generated by protoc-gen-go.
// source: c2s/create.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/create.proto

It has these top-level messages:
	Create
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Create struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Index            *int32  `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	Sex              *int32  `protobuf:"varint,3,req,name=sex" json:"sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Create) Reset()         { *m = Create{} }
func (m *Create) String() string { return proto.CompactTextString(m) }
func (*Create) ProtoMessage()    {}

func (m *Create) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Create) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Create) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}
