// Code generated by protoc-gen-go.
// source: c2s/enterbase.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/enterbase.proto

It has these top-level messages:
	Enterbase
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Enterbase struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Key              *int32  `protobuf:"varint,2,req,name=key" json:"key,omitempty"`
	Rolename         *string `protobuf:"bytes,3,opt,name=rolename" json:"rolename,omitempty"`
	Roleindex        *int32  `protobuf:"varint,4,opt,name=roleindex" json:"roleindex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Enterbase) Reset()         { *m = Enterbase{} }
func (m *Enterbase) String() string { return proto.CompactTextString(m) }
func (*Enterbase) ProtoMessage()    {}

func (m *Enterbase) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Enterbase) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Enterbase) GetRolename() string {
	if m != nil && m.Rolename != nil {
		return *m.Rolename
	}
	return ""
}

func (m *Enterbase) GetRoleindex() int32 {
	if m != nil && m.Roleindex != nil {
		return *m.Roleindex
	}
	return 0
}
