// Code generated by protoc-gen-go.
// source: c2s/loginuser.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/loginuser.proto

It has these top-level messages:
	Loginuser
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Loginuser struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Loginuser) Reset()         { *m = Loginuser{} }
func (m *Loginuser) String() string { return proto.CompactTextString(m) }
func (*Loginuser) ProtoMessage()    {}

func (m *Loginuser) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Loginuser) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}
