// Code generated by protoc-gen-go.
// source: c2s/motion.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/motion.proto

It has these top-level messages:
	Motion
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Motion struct {
	X                *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
	Dir              *float32 `protobuf:"fixed32,4,req,name=dir" json:"dir,omitempty"`
	State            *string  `protobuf:"bytes,5,req,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Motion) Reset()         { *m = Motion{} }
func (m *Motion) String() string { return proto.CompactTextString(m) }
func (*Motion) ProtoMessage()    {}

func (m *Motion) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Motion) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Motion) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *Motion) GetDir() float32 {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return 0
}

func (m *Motion) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}
