// Code generated by protoc-gen-go.
// source: c2s/reqoperatemail.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/reqoperatemail.proto

It has these top-level messages:
	Reqoperatemail
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Reqoperatemail struct {
	Mails            []int64 `protobuf:"varint,1,rep,name=mails" json:"mails,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Reqoperatemail) Reset()         { *m = Reqoperatemail{} }
func (m *Reqoperatemail) String() string { return proto.CompactTextString(m) }
func (*Reqoperatemail) ProtoMessage()    {}

func (m *Reqoperatemail) GetMails() []int64 {
	if m != nil {
		return m.Mails
	}
	return nil
}
