// Code generated by protoc-gen-go.
// source: c2s/selectuser.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/selectuser.proto

It has these top-level messages:
	Selectuser
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Selectuser struct {
	Rolename         *string `protobuf:"bytes,1,req,name=rolename" json:"rolename,omitempty"`
	Roleindex        *int32  `protobuf:"varint,2,req,name=roleindex" json:"roleindex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Selectuser) Reset()         { *m = Selectuser{} }
func (m *Selectuser) String() string { return proto.CompactTextString(m) }
func (*Selectuser) ProtoMessage()    {}

func (m *Selectuser) GetRolename() string {
	if m != nil && m.Rolename != nil {
		return *m.Rolename
	}
	return ""
}

func (m *Selectuser) GetRoleindex() int32 {
	if m != nil && m.Roleindex != nil {
		return *m.Roleindex
	}
	return 0
}
