// Code generated by protoc-gen-go.
// source: c2s/synctime.proto
// DO NOT EDIT!

/*
Package c2s is a generated protocol buffer package.

It is generated from these files:
	c2s/synctime.proto

It has these top-level messages:
	Synctime
*/
package c2s

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Synctime struct {
	ServerTime       *int32 `protobuf:"varint,1,req,name=serverTime" json:"serverTime,omitempty"`
	ClientTime       *int32 `protobuf:"varint,2,req,name=clientTime" json:"clientTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Synctime) Reset()         { *m = Synctime{} }
func (m *Synctime) String() string { return proto.CompactTextString(m) }
func (*Synctime) ProtoMessage()    {}

func (m *Synctime) GetServerTime() int32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *Synctime) GetClientTime() int32 {
	if m != nil && m.ClientTime != nil {
		return *m.ClientTime
	}
	return 0
}
