// Code generated by data parser.
// DO NOT EDIT!
package entity

import (
	. "data/datatype"
	"errors"
	"database/sql"
	"database/sql/driver"
	"encoding/gob"
)

var (
	ErrRowError = errors.New("row index out of range")
	ErrColError = errors.New("col index out of range")
	ErrTypeMismatch = errors.New("val type mismatch")
	ErrColTypeError = errors.New("column type error")
	ErrPropertyNotFound = errors.New("property not found")
	ErrSqlRowError = errors.New("sql query not found")
	ErrSqlUpdateError   = errors.New("update id not found")
	ErrContainerFull	= errors.New("container is full")
	ErrContainerIndexHasChild = errors.New("container index not empty")
	ErrContainerIndexOutOfRange = errors.New("container index out of range")
	ErrContainerNotInit = errors.New("container not init")
	ErrContainerCapacity = errors.New("capacity illegal")
	ErrChildObjectNotFound = errors.New("child obj not found")
	ErrCopyObjError = errors.New("type not equal")
	ErrExtraDataError = errors.New("extra data not found")
)

type ExecQueryer interface {
	Exec(query string, args ...interface{}) (result driver.Result, err error)
	Query(query string, args ...interface{}) (row *sql.Rows, err error)
	GetDB() *sql.DB
}

type DBSaveLoader interface {
	Base() string
	Update(eq ExecQueryer, dbId uint64, extfields string, extplacehold string, extobjs ...interface{}) error
	Insert(eq ExecQueryer, dbId uint64, extfields string, extplacehold string, extobjs ...interface{}) error
	Load(eq ExecQueryer, dbId uint64, extfield string, extobjs ...interface{}) error
	Marshal() (map[string]interface{}, error)
	Unmarshal(data map[string]interface{}) error 
}

type Recorder interface {
	GetName() string
	GetCap() int
	GetCols() int
	GetRows() int
	ColTypes() ([]int, []string)
	IsDirty() bool
	IsSave() bool
	IsVisible() bool
	ClearDirty()
	Set(row, col int, val interface{}) error
	Get(row, col int) (val interface{}, err error)
	SetRow(row int, args ...interface{} ) error
	GetRowInterface(row int)(rowvalue interface{}, err error)
	Add(row int, args ...interface{} ) int
	AddRow(row int) int
	Del(row int)
	Clear()
	SetSyncer(s TableSyncer)
	GetSyncer() TableSyncer
	Serial() ([]byte, error)
	SerialRow(row int) ([]byte, error)
}

type TableSyncer interface {
	RecAppend(rec Recorder, row int)
	RecDelete(rec Recorder, row int)
	RecClear(rec Recorder)
	RecModify(rec Recorder, row, col int)
	RecSetRow(rec Recorder, row int)
}

type PropSyncer interface {
	Update(index int16, value interface{})
}

type PropHooker interface {
	OnPropChange(object Entityer, prop string, value interface{})
}

type EntityInfo struct {
	Type     string
	Caps     int32
	DbId     uint64
	ObjId    ObjectID
	Index    int
	Data     []byte
	Childs   []*EntityInfo
}

type Entityer interface {
	SetPropSyncer(sync PropSyncer)
	GetPropSyncer()PropSyncer
	SetPropHooker(hooker PropHooker)
	GetPropFlag(idx int) bool
	SetPropFlag(idx int, flag bool)
	IsCritical(idx int) bool
	SetCritical(prop string)
	ClearCritical(prop string)
	SetLoading(loading bool)
	IsLoading() bool
	SetQuiting()
	IsQuiting() bool
	GetConfig() string
	SetConfig(config string)
	SetSaveFlag()
	ClearSaveFlag()
	NeedSave() bool
	GetRoot() Entityer
 	SetParent(p Entityer)
 	GetParent() Entityer
	SetDeleted(d bool)
	GetDeleted() bool
	SetObjId(id ObjectID)
	GetObjId() ObjectID
	SetNameHash(v int32) 
	GetIDHash() int32 
	IDEqual(id string) bool
	GetNameHash() int32
	NameEqual(name string) bool
	SetCapacity(capacity int32, initcap int32)
	ChangeCapacity(capacity int32) error
	GetCapacity() int32
	GetRealCap() int32
	ChildCount() int
	GetChilds() []Entityer
	GetIndex() int
	SetIndex(idx int)
	ClearChilds()
	AddChild(idx int,e Entityer) (index int, err error)
	RemoveChild(e Entityer) error
	GetChild(idx int) Entityer
	GetChildByConfigId(id string) Entityer
	GetFirstChildByConfigId(id string) (int, Entityer)
	GetNextChildByConfigId(start int, id string) (int, Entityer)
	GetChildByName(name string) Entityer
	GetFirstChild(name string) (int, Entityer)
	GetNextChild(start int, name string) (int, Entityer)
	SwapChild(src int, dest int) error
	SetExtraData(key string, value interface{})
	GetExtraData(key string) interface{}
	GetAllExtraData() map[string]interface{} 
	RemoveExtraData(key string)
	ClearExtraData()
	ObjType() int
	Base() Entityer
	GetDbId() uint64
	SetDbId(id uint64)
	IsSave() bool 
	SetSave(s bool) 
	ObjTypeName() string
	//property
	GetPropertys() []string
	GetVisiblePropertys(typ int) []string
	GetPropertyType(p string) (int, string, error)
	GetPropertyIndex(p string) (int, error)
	Inc(p string, v interface{}) error
	Set(p string, v interface{}) error
	MustGet(p string) interface{}
	Get(p string) (val interface{}, err error)
	PropertyIsPublic(p string) bool
	PropertyIsPrivate(p string) bool
	PropertyIsSave(p string) bool
	GetDirty() map[string]interface{}
	ClearDirty()
	GetModify() map[string]interface{}
	ClearModify()
	//record
	GetRec(rec string) Recorder
	GetRecNames() []string
	Reset()
	Copy(other Entityer) error
	//DB
	SyncToDb()
	GetConfigFromDb(data interface{}) string
	SyncFromDb(data interface{})bool
	GetSaveLoader() DBSaveLoader
	Serial()([]byte, error)
	SerialModify()([]byte, error)
}

var objects = make(map[string]func() Entityer)

//注册函数
func register(name string, createfunc func() Entityer) {
	if _, dup := objects[name]; dup {
		panic("entity: Register called twice for object " + name)
	}
	objects[name] = createfunc
}

//创建数据对象
func Create(name string) Entityer {
	if create, exist := objects[name]; exist {
		return create()
	}

	return nil
}

//获取类型
func GetType(name string) int {
	switch name { {{range .}}
	case "{{.Name}}":
		return {{.Type}}{{end}}
	default:
		return NONE
	}
}

func CreateSaveLoader(typ string) DBSaveLoader {
	switch typ { {{range .}}
	case "{{.Name}}":
		return &{{.Name}}_Save{}{{end}}
	default:
		return nil
	}
}

func Hash(str string) int32 {
	hash := 5381
	for _, c := range str {
		hash += (hash << 5) + int(c)
	}

	return int32(hash & 0x7FFFFFFF)
}

{{range .}}
func Is{{.Name}}(ent Entityer) bool {
		return ent.ObjTypeName()=="{{.Name}}"
}
{{end}}

//初始化函数
func init() {
	{{range .}}
	register("{{.Name}}", func() Entityer {
		return Create{{.Name}}()
	})
	{{.Name}}Init()
	{{end}}

	gob.Register(&EntityInfo{})
}
